{% set name = "tagref" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stepchowfun/tagref/archive/v{{ version }}.tar.gz
  sha256: 47d18c8fe3b037fd32fbeeeb91cf763840a809050a82a386dd56f73505a375fd

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - tagref --help

about:
  home: https://github.com/stepchowfun/tagref
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Refer to other locations in your codebase
  dev_url: https://github.com/stepchowfun/tagref

extra:
  recipe-maintainers:
    - danielnachun
