context:
  version: "1.12.1"

package:
  name: tagref
  version: ${{ version }}

source:
  url: https://github.com/stepchowfun/tagref/archive/v${{ version }}.tar.gz
  sha256: 3d0017911afb6d9b887444c6da32f1642ad4046b4098af3d412fae1b58fece8c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tagref --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Refer to other locations in your codebase
  homepage: https://github.com/stepchowfun/tagref
  repository: https://github.com/stepchowfun/tagref

extra:
  recipe-maintainers:
    - danielnachun
