context:
  version: "1.11.0"

package:
  name: tagref
  version: ${{ version }}

source:
  url: https://github.com/stepchowfun/tagref/archive/v${{ version }}.tar.gz
  sha256: a5172df6b7e3c943d9c805ffd31ec4b00d226c34c989b9c3cefe29eb0499361c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tagref --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Refer to other locations in your codebase
  homepage: https://github.com/stepchowfun/tagref
  repository: https://github.com/stepchowfun/tagref

extra:
  recipe-maintainers:
    - danielnachun
