context:
  version: "1.12.0"

package:
  name: tagref
  version: ${{ version }}

source:
  url: https://github.com/stepchowfun/tagref/archive/v${{ version }}.tar.gz
  sha256: cbed599298e23ed526c9f6d5463eaf203cb75a88797ac2609e5eb45111451b8d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - tagref --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Refer to other locations in your codebase
  homepage: https://github.com/stepchowfun/tagref
  repository: https://github.com/stepchowfun/tagref

extra:
  recipe-maintainers:
    - danielnachun
